leftnav:
- identifier: b55da6e9-2637-4ecf-b526-5e543a9cda26
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 6feef223-7c47-4a8e-9f77-83ea0242ae2d
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 5766748f-26ce-4690-8413-aba30fb6b353
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: c6704126-7f51-47fd-a4df-f8bbd014859a
  name: Lecture Slides
  url: /pages/lecture-slides
  weight: 40
